#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_PATH="${CONFIG_PATH:-/tmp/nzbdav-config}"
BACKEND_URL="${BACKEND_URL:-http://localhost:5000}"
API_KEY_FILE="$CONFIG_PATH/.frontend-backend-api-key"
FRONTEND_ENV_FILE="$ROOT_DIR/frontend/.env"

if [[ -z "${FRONTEND_BACKEND_API_KEY:-}" ]]; then
  if [[ -f "$API_KEY_FILE" ]]; then
    FRONTEND_BACKEND_API_KEY="$(tr -d '[:space:]' < "$API_KEY_FILE")"
  else
    FRONTEND_BACKEND_API_KEY="$(head -c 32 /dev/urandom | hexdump -ve '1/1 "%.2x"')"
    mkdir -p "$CONFIG_PATH"
    printf '%s\n' "$FRONTEND_BACKEND_API_KEY" > "$API_KEY_FILE"
    echo "Created API key at $API_KEY_FILE"
    echo "Restart the backend with ./scripts/run-backend.sh so it uses the same key."
  fi
fi

mkdir -p "$CONFIG_PATH"

cat > "$FRONTEND_ENV_FILE" <<EOF
# Generated by scripts/sync-dev-env.sh — override in frontend/.env.local
NODE_ENV=development
PORT=5173
BACKEND_URL=$BACKEND_URL
FRONTEND_BACKEND_API_KEY=$FRONTEND_BACKEND_API_KEY
EOF

echo "Synced $FRONTEND_ENV_FILE"
