name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create release
        uses: googleapis/release-please-action@v5
        id: release
        with:
          config-file: .release-please-config.json

  deploy:
    if: ${{ needs.release.outputs.release_created }}
    needs: release
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    with:
      tags: |
        ghcr.io/${{ github.repository }}:latest
        ghcr.io/${{ github.repository }}:${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }}
        ghcr.io/${{ github.repository }}:${{ needs.release.outputs.major }}.x
        ghcr.io/${{ github.repository }}:${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.x
      nzbdav_version: ${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }}
      checkout_ref: ${{ needs.release.outputs.sha }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
